# Generated by Django 5.2.7 on 2025-11-30 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BOLETIM', 'Boletim Escolar'), ('DECLARACAO', 'Declaração de Matrícula'), ('HISTORICO', 'Histórico Escolar Completo'), ('CERTIFICADO', 'Certificado de Conclusão')], max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('codigo_validacao', models.CharField(editable=False, max_length=32, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='academico.aluno')),
                ('solicitante', models.ForeignKey(help_text='Quem pediu o documento (o próprio aluno ou secretaria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Emitido',
                'verbose_name_plural': 'Documentos Emitidos',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
