# Generated by Django 5.2.8 on 2025-11-14 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registro_administrativo', models.CharField(max_length=50, unique=True)),
                ('nivel_acesso', models.CharField(max_length=50)),
                ('area_coordenacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_funcao', models.DateField(blank=True, null=True)),
                ('pode_finalizar_boletim', models.BooleanField(default=False)),
                ('pode_aprovar_turma', models.BooleanField(default=False)),
                ('pode_gerenciar_perfis', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coordenação',
                'verbose_name_plural': 'Coordenação',
                'db_table': 'academico_coordenacao',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'academico_endereco',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_telefone', models.CharField(max_length=20)),
                ('tipo_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
                'db_table': 'academico_telefone',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=100, unique=True)),
                ('cod_departamento', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status_ativo', models.BooleanField(default=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.coordenacao')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'academico_departamento',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.CharField(max_length=50, unique=True)),
                ('nome_curso', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('carga_horaria_total', models.IntegerField()),
                ('modalidade', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('data_inicio_validade', models.DateField(blank=True, null=True)),
                ('credenciamento_ativo', models.BooleanField(default=True)),
                ('cod_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.departamento')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'academico_curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('status_curricular', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_requisito_disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_requisito_para', to='academico.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'academico_disciplina',
            },
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_curso', models.IntegerField(blank=True, null=True)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('status_na_matriz', models.CharField(default='Ativo', max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina do Curso',
                'verbose_name_plural': 'Disciplinas do Curso',
                'db_table': 'academico_curso_disciplina',
                'unique_together': {('curso', 'disciplina')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(related_name='cursos', through='academico.CursoDisciplina', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='coordenacao',
            name='cod_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registro_funcional', models.CharField(max_length=50, unique=True)),
                ('formacao', models.CharField(max_length=100)),
                ('tipo_vinculo', models.CharField(max_length=50)),
                ('data_contratacao', models.DateField()),
                ('status_professor', models.CharField(default='Ativo', max_length=20)),
                ('is_proponente_turma', models.BooleanField(default=False)),
                ('etnia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('deficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.departamento')),
                ('cod_endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'academico_professor',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('nome_completo_responsavel', models.CharField(max_length=150)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('contato_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('cod_endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco')),
                ('telefones', models.ManyToManyField(blank=True, to='academico.telefone')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'db_table': 'academico_responsavel',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('RA_aluno', models.CharField(max_length=50, unique=True)),
                ('RG_aluno', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('etinia', models.CharField(blank=True, max_length=50, null=True)),
                ('deficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(max_length=20)),
                ('conclusao_EM', models.DateField(blank=True, null=True)),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status_matricula', models.CharField(default='Ativo', max_length=20)),
                ('cod_endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco')),
                ('responsavel_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.responsavel')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'academico_aluno',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registro_administrativo', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('data_inicio_cargo', models.DateField(blank=True, null=True)),
                ('pode_gerenciar_perfis', models.BooleanField(default=True)),
                ('pode_acessar_relatorios_financeiros', models.BooleanField(default=False)),
                ('cod_endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretaria',
                'db_table': 'academico_secretaria',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('periodo', models.CharField(max_length=50)),
                ('ano_letivo', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('capacidade_maxima', models.IntegerField(default=40)),
                ('alunos_matriculados', models.IntegerField(default=0)),
                ('status_aprovacao', models.CharField(default='Pendente', max_length=50)),
                ('coordenacao_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.coordenacao')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'academico_turma',
            },
        ),
        migrations.CreateModel(
            name='RegistroOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status_intervencao', models.CharField(default='Pendente', max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
                ('coordenacao_revisou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.coordenacao')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.professor')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.turma')),
            ],
            options={
                'verbose_name': 'Registro de Ocorrência',
                'verbose_name_plural': 'Registros de Ocorrência',
                'db_table': 'academico_registro_ocorrencia',
            },
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_referencia', models.CharField(max_length=50)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('status_boletim', models.CharField(default='Em Aberto', max_length=50)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_coordenacao', models.TextField(blank=True, null=True)),
                ('coordenacao_finalizou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.coordenacao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'verbose_name': 'Boletim',
                'verbose_name_plural': 'Boletins',
                'db_table': 'academico_boletim',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academico.turma'),
        ),
        migrations.CreateModel(
            name='TurmaDisciplinaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_alocacao', models.CharField(default='Alocado', max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'verbose_name': 'Alocação Professor-Turma-Disciplina',
                'verbose_name_plural': 'Alocações',
                'db_table': 'academico_turma_disciplina_professor',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('media_final', models.FloatField(blank=True, null=True)),
                ('frequencia_percentual', models.FloatField(blank=True, null=True)),
                ('total_faltas', models.IntegerField(blank=True, null=True)),
                ('status_aprovacao', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_realizacao', models.CharField(max_length=50)),
                ('data_lancamento', models.DateTimeField(auto_now=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='academico.aluno')),
                ('turma_disciplina_professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.turmadisciplinaprofessor')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
                'db_table': 'academico_historico',
                'unique_together': {('id_aluno', 'turma_disciplina_professor')},
            },
        ),
    ]
