# Generated by Django 5.2.7 on 2025-12-07 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='RG_aluno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cod_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coordenacao',
            name='nivel_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coordenacao',
            name='registro_administrativo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cod_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.departamento'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cod_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.endereco'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='formacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='registro_funcional',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='tipo_vinculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='registro_administrativo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
