# Generated by Django 5.2.7 on 2025-12-01 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('Urgente', 'Urgente'), ('Importante', 'Importante'), ('Geral', 'Geral'), ('Informativo', 'Informativo')], default='Geral', max_length=20)),
                ('tipo_usuario_criador', models.CharField(choices=[('professor', 'Professor'), ('coordenacao', 'Coordenação'), ('secretaria', 'Secretaria')], default='secretaria', max_length=20)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_visibilidade', models.DateTimeField(blank=True, null=True)),
                ('data_fim_visibilidade', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_evento', models.DateTimeField()),
                ('tipo_usuario_criador', models.CharField(choices=[('professor', 'Professor'), ('coordenacao', 'Coordenação'), ('secretaria', 'Secretaria')], default='secretaria', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Acadêmico',
                'verbose_name_plural': 'Eventos Acadêmicos',
                'ordering': ['data_evento'],
            },
        ),
    ]
