# Generated by Django 5.2.7 on 2025-11-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_processados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/Rejeitado por'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação/Rejeição'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='primeiro_nome',
            field=models.CharField(max_length=150, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='sobrenome',
            field=models.CharField(max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status da Solicitação'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='tipo_solicitado',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('secretaria', 'Secretaria'), ('coordenacao', 'Coordenação')], max_length=20, verbose_name='Tipo de Perfil Solicitado'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome de Usuário'),
        ),
        migrations.AlterModelTable(
            name='pendingregistration',
            table='usuarios_pending_registration',
        ),
    ]
