# Generated by Django 5.2.7 on 2025-11-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pendingregistration_bairro_pendingregistration_cep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='endereco',
        ),
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rg', 'RG / Cartão Cidadão'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovativo de Morada'), ('historico', 'Histórico Escolar'), ('foto', 'Foto de Perfil')], max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos_usuarios/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
