# Generated by Django 5.2.7 on 2025-12-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_profile_endereco_profile_bairro_profile_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha Temporária'),
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
