# Generated by Django 5.2.7 on 2025-12-07 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_pendingregistration_senha_profile_endereco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_processados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='primeiro_nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='sobrenome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='tipo_solicitado',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('secretaria', 'Secretaria'), ('coordenacao', 'Coordenação')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
