"""
Django settings for school_manager project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
# Path e dotenv
from pathlib import Path
from dotenv import load_dotenv

# carregar .env (se existir) para facilitar desenvolvimento local
load_dotenv()
# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# Configurações básicas
# ==============================

SECRET_KEY = 'django-insecure-7q()hy)04l-36t=dzf+k%@d9p^bh4#z_hdoqmx9-317*)v#wk#'
DEBUG = True
ALLOWED_HOSTS = ['romulofamiglietti.pythonanywhere.com', '127.0.0.1', 'localhost']

# ==============================
# Asaas Configurações (variáveis através de .env / ambiente)
# Exemplo no .env:
# ASAAS_API_KEY=seu_token_aqui
# ASAAS_WEBHOOK_TOKEN=um_token_aleatorio_para_validar_webhooks
# ASAAS_BASE_URL=https://api-sandbox.asaas.com/v3
# ==============================
ASAAS_API_KEY = os.getenv('ASAAS_API_KEY')
ASAAS_BASE_URL = os.getenv('ASAAS_BASE_URL', 'https://api-sandbox.asaas.com/v3')
ASAAS_WEBHOOK_TOKEN = os.getenv('ASAAS_WEBHOOK_TOKEN')

# ==============================
# Aplicações
# ==============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bibliotecas de terceiros
    'rest_framework',
    'crispy_forms',
    'django_filters',
    'import_export',

    # Seus apps personalizados 
    'apps.usuarios.apps.UsuariosConfig',
    'apps.academico.apps.AcademicoConfig',
    'apps.dashboards.apps.DashboardsConfig',
    'apps.relatorios',
    # App de pagamentos (integração Asaas)
    'apps.payments',
]

# ==============================
# Middleware
# ==============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.usuarios.middleware.LimitUserSessionsMiddleware',
]

ROOT_URLCONF = 'school_manager.urls'

# ==============================
# Templates
# ==============================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_manager.wsgi.application'

# ==============================
# Banco de Dados
# ==============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'senai.db',
    }
}

# ==============================
# Internacionalização
# ==============================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==============================
# Arquivos estáticos e mídia
# ==============================

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==============================
# Autenticação e Redirecionamento
# ==============================

LOGIN_REDIRECT_URL = 'redirecionar_dashboard'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# ==============================
# Configurações de Sessão (ATUALIZADO)
# ==============================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_SAVE_EVERY_REQUEST = False  # Não salvar a cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Manter sessão após fechar navegador
SESSION_COOKIE_HTTPONLY = True  # Segurança: JS não acessa cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Proteção contra CSRF
SESSION_COOKIE_SECURE = False  # Mudar para True em produção com HTTPS

# ==============================
# Configurações de CSRF (NOVO)
# ==============================

CSRF_COOKIE_AGE = 31449600  # 1 ano (365 dias)
CSRF_USE_SESSIONS = False  # Usar cookie ao invés de sessão
CSRF_COOKIE_HTTPONLY = False  # JavaScript precisa ler o token
CSRF_COOKIE_SAMESITE = 'Lax'  # Proteção contra ataques CSRF
CSRF_COOKIE_SECURE = False  # Mudar para True em produção com HTTPS
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

# ==============================
# Mensagens
# ==============================

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ==============================
# Cache
# ==============================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ==============================
# Configurações adicionais
# ==============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# ==============================
# Validação de Senhas
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,  # Mínimo 4 caracteres para testes
        }
    },
]

# ==============================
# Limpeza Automática de Sessões
# ==============================

# Limpar sessões expiradas automaticamente
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_AGE = 86400  # 24 horas

# Configuração adicional para debug
if DEBUG:
    # Em desenvolvimento, limitar vida útil da sessão
    SESSION_COOKIE_AGE = 3600  # 1 hora