"""
Django settings for school_manager project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis de ambiente do arquivo .env na raiz
load_dotenv(BASE_DIR / '.env')

# ==============================
# Configurações básicas
# ==============================

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7q()hy)04l-36t=dzf+k%@d9p^bh4#z_hdoqmx9-317*)v#wk#')

# Em produção no PythonAnywhere, defina DEBUG como False no seu arquivo .env
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ATUALIZADO: Adicionado seu domínio
ALLOWED_HOSTS = ['leomeriva.pythonanywhere.com', '127.0.0.1', 'localhost']

# ==============================
# Configurações do Stripe
# ==============================
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_51SZC0Z13heh5oTSzLZKZbWaX9UlDU0tDkngjbnFg4QIGvEnYHMYC7Fncq9sFXdOGXYdtxZaae8vBGpRwW2qJcxF300LPOkDja4')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51SZC0Z13heh5oTSzVtxQbxTrtzRyOqpiXnyb23TOjUYzUNnBaqdvQID5ltjrFHBFYZlSnnZIJuPg0zKzrIa0GltA00bfbODh1p')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_teste_local_12345')

# ==============================
# Aplicações
# ==============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bibliotecas de terceiros
    'rest_framework',
    'crispy_forms',
    'django_filters',
    'import_export',

    # Seus apps personalizados 
    'apps.usuarios.apps.UsuariosConfig',
    'apps.academico.apps.AcademicoConfig',
    'apps.dashboards.apps.DashboardsConfig',
    'apps.relatorios',
    # App de pagamentos (integração Stripe)
    'apps.payments',
]

# ==============================
# Middleware
# ==============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.usuarios.middleware.LimitUserSessionsMiddleware',
]

ROOT_URLCONF = 'school_manager.urls'

# ==============================
# Templates
# ==============================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_manager.wsgi.application'

# ==============================
# Banco de Dados
# ==============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'senai.db',
    }
}

# ==============================
# Internacionalização
# ==============================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==============================
# Arquivos estáticos e mídia
# ==============================

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==============================
# Autenticação e Redirecionamento
# ==============================

LOGIN_REDIRECT_URL = 'redirecionar_dashboard'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# ==============================
# Configurações de Sessão
# ==============================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Mudar para True em produção

# ==============================
# Configurações de CSRF
# ==============================

CSRF_COOKIE_AGE = 31449600
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
# ATUALIZADO: Domínio confiável para o CSRF
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://leomeriva.pythonanywhere.com',
]

# ==============================
# Mensagens
# ==============================

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ==============================
# Cache
# ==============================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ==============================
# Configurações adicionais
# ==============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# ==============================
# Validação de Senhas
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        }
    },
]